- name: deploy newrelic service
  become: yes
  become_user: root
  template:
    src: newrelic.service.j2
    dest: /etc/systemd/system/newrelic.service
  tags:
    - newrelic
  register: newrelic_service

- name: restart newrelic if service changed
  debug: msg="Restart newrelic if service changed"
  tags:
    - newrelic
  notify:
    - reload systemd
    - restart newrelic
  when: newrelic_service.changed
  
# Attach to the running container, or start it if needed
# and forward all signals so that the process manager can detect
# when a container stops and correctly restart it.
- name: ensure newrelic is running (and enable it at boot)
  become: yes
  service:
    name: newrelic
    state: started
    enabled: yes
  tags:
    - newrelic
